import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'
import StoryblokProvider from '@/src/components/storyblok-provider'

storyblokInit({
  accessToken: 'm2nlCckFxnPrXV5yxQh3qwtt',
  use: [apiPlugin]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={'bg-red-100 min-h-screen h-full'}>{children}</body>
      </html>
    </StoryblokProvider>
  )
}
